### ISSUE TITLE
Calling for a specific branch does not seem to work

### ISSUE THREAD

**Issue by mickmcgrath13** [bitovi/github-actions-deploy-ops-repo#2]
tested with a pipeline in the ops repo that had not been created in `main`, yet
- create branch in ops repo
- create a new pipeline in ops repo
- try to trigger pipeline as follows:
```
  deploy:
    # only deploy if not pull request
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stage
        uses: bitovi/github-actions-bitops-ci-cd@0.5.0
        with:
          github-token: ${{ secrets.OPERATIONS_REPO_TOKEN }}
          org: bitovi
          repo: operations-repo
          branch: some-branch
          workflow: new-workflow.yaml
```
